export const projects = [
  {
    title: "Aurórá - An online YouTube Video Player",
    date: "Feb 2023",
    description:
      "Aurórá, is an online YouTube video player made using ReactJs. It uses YouTube API to fetch YouTube videos and channels. Users can search for their favourite creator's channel and videos, play them and can also login through super fast and reliable Firebase's Google authentication and add videos to the watchlist to save them from hassle of searching that favourite video again in future to watch, and login from any device to access your watchlist(Firestore's amazing!! Isn't it!!). The WebApp has minimal design and UI is kept similar to YouTube's UI so that the users don't get lost in figuring out how to play/pause a video instead of enjoying them. Chreers!",
    techStack: [
      "React",
      "Javascript",
      "Material UI v5",
      "Redux-Toolkit",
      "HTML",
      "NodeJs",
      "Firebase",
      "Firestore",
      "Vite",
      "YouTube API",
    ],
    liveLink: "https://aurora-onlinevideoplayer-prabhat18.netlify.app/",
    gitHubLink: "https://github.com/Gohan-18/Video-Player",
    youtubeLink: "https://www.youtube.com/watch?v=5mJBauLcYp4&t=1648s",
  },
  {
    title: "ShopMore - An online Marketplace",
    date: "Jan 2023",
    description: "ShopMore, an E-Commerce website made using ReactJs.",
    techStack: [
      "React",
      "Javascript",
      "Material UI v5",
      "Redux-Toolkit",
      "HTML",
      "NodeJs",
      "Firebase",
      "Formspree",
      "Vite",
    ],
    liveLink: "https://shopmore-prabhat18.netlify.app/",
    gitHubLink: "https://github.com/Gohan-18/Shopping-website",
    youtubeLink: "https://www.youtube.com/watch?v=5mJBauLcYp4&t=1648s",
  },
  {
    title: "Note Taking App",
    date: "Nov 2022",
    description:
      "Made a full fledged note taking app using React. Made it to get some hands on creating CRUD based apps. The user can create a note, give it a title and the main content, update the content and title and also can delete it completely. They can also search any note by their title through the search bar given at the top. And yeah, almost forgot... the content won't get deleted after the page refresh(used LocalStorage to achieve that). Cheers!!",
    techStack: ["React", "Javascript", "HTML", "CSS", "NodeJs", "Vite"],
    liveLink: "https://note-app-prabhat18.netlify.app/",
    gitHubLink: "https://github.com/Gohan-18/Note-Taking_App",
    youtubeLink: "https://www.youtube.com/watch?v=5mJBauLcYp4&t=1648s",
  },
  {
    title: "Chróma - An Image Searching App",
    date: "Nov 2022",
    description:
      "It's an image searching webApp made with HTML, CSS and vanilla JavaScript. Here the user can search for any image of their liking by typing the desired keyword in the input box on the home page. It uses UnSplash API to fetch the searched image and show it to the user.",
    techStack: ["Javascript", "HTML", "CSS", "NodeJs"],
    liveLink: "https://chroma-animagesearchingapp.netlify.app/",
    gitHubLink: "https://github.com/Gohan-18/Gallary-App/tree/main/Gallary-App",
    youtubeLink: "https://www.youtube.com/watch?v=5mJBauLcYp4&t=1648s",
  },
];
